name = "meidasupport-frontend"
compatibility_date = "2023-08-01"

[env.production]
account_id = "your-account-id"
compatibility_date = "2023-08-01"

[env.production.vars]
ENVIRONMENT = "production"

# Pages 配置
[build]
command = ""
cwd = ""
watch_dir = ""

# 路由配置
[[routes]]
pattern = "/api/*"
zone_name = "your-domain.com"

# 自定义头部
[headers]
"/*" = { "X-Frame-Options" = "DENY", "X-Content-Type-Options" = "nosniff" }
"/static/*" = { "Cache-Control" = "public, max-age=31536000" } 